apiVersion: v1
kind: Service
metadata:
  name: bdd-service
spec:
  type: NodePort
  selector:
    app: bdd-service
  ports:
  - protocol: TCP
    port: 5000       # Port inside the cluster
    targetPort: 5000  # Port on the pod
    # nodePort: 30002 # Optional: specify a NodePort, or let K8s assign one
                      # For now, let K8s assign.
