apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:4.17.0
        ports:
        - containerPort: 4444 # Default Selenium Hub port
        - containerPort: 4442 # Event Bus Publish port
        - containerPort: 4443 # Event Bus Subscribe port
