apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  type: LoadBalancer
  selector:
    app: selenium-hub
  ports:
  - name: hub-port
    protocol: TCP
    port: 4444       # Port inside the cluster
    targetPort: 4444  # Port on the pod
  - name: bus-publish-port
    protocol: TCP
    port: 4442
    targetPort: 4442
  - name: bus-subscribe-port
    protocol: TCP
    port: 4443
    targetPort: 4443
