- hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Bootstrap Python 3.8 using raw command
      raw: |
        amazon-linux-extras enable python3.8
        yum clean metadata
        yum install -y python3.8
        ln -sf /usr/bin/python3.8 /usr/bin/python3
      register: python_install
      changed_when: "'Complete!' in python_install.stdout"

    - name: Set Python 3.8 as the interpreter
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Manually gather facts using new interpreter
      setup:

  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Run Selenium Hub container
      shell: docker run -d --restart always -p 4444:4444 --name selenium-hub selenium/hub:4.17.0
      args:
        creates: /var/lib/docker/containers

    - name: Run Selenium Node Chrome container
      shell: docker run -d --restart always --link selenium-hub:hub selenium/node-chrome:4.17.0
      args:
        creates: /var/lib/docker/containers

