- hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Selenium Hub container
      shell: docker run -d --restart always -p 4444:4444 --name selenium-hub selenium/hub:4.17.0
      args:
        creates: /var/lib/docker/containers

    - name: Run Selenium Node Chrome container
      shell: docker run -d --restart always --link selenium-hub:hub selenium/node-chrome:4.17.0
      args:
        creates: /var/lib/docker/containers

    - name: List running Docker containers
      shell: docker ps