- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Run Selenium Hub container
      shell: docker run -d -p 4444:4444 --name selenium-hub selenium/hub:latest
      args:
        creates: /var/lib/docker/containers

    - name: Run Selenium Node Chrome container
      shell: docker run -d --link selenium-hub:hub selenium/node-chrome:latest
      args:
        creates: /var/lib/docker/containers