name: Deploy Selenium Grid

on:
  workflow_dispatch:

concurrency:
  group: terraform-selenium
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Write tfvars with SSH keys
        run: |
          echo "ssh_public_key = \"${{ secrets.SSH_PUBLIC_KEY }}\"" > terraform/terraform.tfvars
          echo 'ssh_private_key = <<EOKEY' >> terraform/terraform.tfvars
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" >> terraform/terraform.tfvars
          echo 'EOKEY' >> terraform/terraform.tfvars

      - name: Terraform Plan
        run: terraform -chdir=terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve -var-file=terraform.tfvars

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible sshpass

      - name: Create inventory file
        run: |
          echo "[all]" > ansible/inventory.ini
          terraform -chdir=terraform output -raw instance_ip >> ansible/inventory.ini

      - name: Inject SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$(terraform -chdir=terraform output -raw instance_ip) echo "SSH Success"

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/playbook.yml --private-key ~/.ssh/id_rsa -u ubuntu

      - name: Cleanup tfvars
        run: rm -f terraform/terraform.tfvars

      - name: Cleanup SSH Key
        run: rm -f ~/.ssh/id_rsa